# Generated by Django 3.1.1 on 2020-10-02 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('total_feature', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('date_built', models.DateTimeField()),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('house_type', models.CharField(max_length=100)),
                ('street_no', models.IntegerField()),
                ('property_size', models.CharField(max_length=10, null=True)),
                ('property_type', models.CharField(max_length=100, null=True)),
                ('features', models.ManyToManyField(to='estateapp.HomeFeatures')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateapp.userprofile')),
            ],
        ),
    ]
