# Generated by Django 3.1.1 on 2020-10-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefeatures',
            name='total_feature',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
