# Generated by Django 3.1.1 on 2020-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_auto_20201002_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefeatures',
            name='total_feature',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
