# Generated by Django 3.1.1 on 2020-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0003_auto_20201002_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='file',
            field=models.FileField(default='null', upload_to='property'),
            preserve_default=False,
        ),
    ]
