# Generated by Django 3.1.1 on 2020-10-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0004_home_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homefeatures',
            options={'verbose_name_plural': 'Home Features'},
        ),
    ]
